apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.common.name}}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.common.name}}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: http-port
    - from:
        - podSelector: {}
    - from:
        - namespaceSelector: {}
  egress:
    - to:
        - podSelector: { }
    - to:
        - namespaceSelector: { }