apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.common.name }}-secret
  labels:
    commit: {{ .Chart.AppVersion }}
    app: {{ .Values.common.name }}
type: Opaque
data:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}